// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function Open():Promise<{[key: string]: any}>;

export function Save(arg1:{[key: string]: any}):void;

export function ShowDialog():void;
